name: Сборка проекта

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v2
        
      - name: Установка зависимостей
        run: |
          sudo apt-get update
          sudo apt-get install -y libsfml-dev
          sudo apt-get install -y libgtest-dev
          sudo apt-get install -y cmake
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp *.a /usr/lib
          cd -
      
      - name: Сборка проекта
        run: |
          mkdir build
          cd build
          cmake ..
          make
          cd ..
      
      - name: Запуск тестов
        run: |
          cd build
          ctest -V
